###
GET http://localhost:4000/


###
POST http://localhost:4000/api/info
Content-Type: application/json

{
    "information": "My name is Varun"
}

###
PUT http://localhost:4000/api/?word=varun&banana=ripe
# Content-Type: application/json

# {
#     "information": "My name is Varun"
# }


###
DELETE http://localhost:4000/delete/6/neat
